### ISSUE TITLE
Error prop

### ISSUE THREAD

**Issue by voby** [ErrorPro/relay-compose#1]
https://github.com/ErrorPro/relay-compose/blob/44ebc762a48360c770969b51c2d274f445e36aa5/src/index.js#L47
https://github.com/ErrorPro/relay-compose/blob/44ebc762a48360c770969b51c2d274f445e36aa5/src/index.js#L39

Error prop will be always null in base component. If an error occurs, render function will return null.

**Comment by ErrorPro** [comment]
Yep, that makes sense. I'll check it later and think what can be done to fix it. Thanks.

**Comment by ErrorPro** [comment]
@voby Can you check it now please?

**Comment by voby** [comment]
@ErrorPro LFTM
