### ISSUE TITLE
Errors missing in mutation

### ISSUE THREAD

**Issue by jkettmann** [ErrorPro/relay-compose#3]
In Relay modern the `onCompleted` callback for [mutations accepts two parameters](https://facebook.github.io/relay/docs/mutations.html). First is the result, second an array of errors. Since `createMutation` [uses a promise](https://github.com/ErrorPro/relay-compose/blob/master/src/index.js#L76) only the result is passed to `then`, but not the errors.

Following might be two implementations. I'd prefer the second one, since it's counter intuitive to get errors in the onCompleted callback anyways, but this would be quite different from the usual Relay mutation API of course. [Compare relay-commit-mutation-promise](https://github.com/robrichard/relay-commit-mutation-promise/blob/master/index.js) 

```
onCompleted: (result, errors) => res({ result, errors })
```

```
onCompleted: (result, errors) => {
  if (errors) rej(errors)
  else res(result)
}
```

**Comment by ErrorPro** [comment]
@jkettmann Thanks for your issue, I will check it and fix asap.

**Comment by ErrorPro** [comment]
@jkettmann check please 1.0.8 version. Thank you.
